name: Build Windows App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install dependencies
      run: |
        npm install -g yarn
        yarn install
        
    - name: Build Electron app
      run: |
        yarn build
        yarn electron-builder --win portable
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: release/*.exe